### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by elbrujohalcon** [amyjko/cooperative-software-development#1]
What do you think about pushing your code to the `gh-pages` branch instead of `master` so that you can take advantage of [Github Pages](https://pages.github.com/) and host the book here?

**Comment by amyjko** [comment]
Interesting idea. Do you see some benefit to readers and other stakeholders hosting it on GitHub instead of my faculty website?

**Comment by elbrujohalcon** [comment]
I didn't know it was hosted anywhere… I found the repo and I didn't find any url pointing to a version that's hosted somewhere. So, to be able to read it, I had to clone it and open it locally.
If it's already hosted somewhere, you should put that url in your repo's description or README.md.

**Comment by elbrujohalcon** [comment]
I went ahead and sent you PR #2 with a very basic README.md linking to your site.

**Comment by amyjko** [comment]
Ah, good catch. Obviously I haven't spent much time maintaining this repo. Thank you!

**Comment by elbrujohalcon** [comment]
Cooperative Software Development at its finest :trollface:
