### ISSUE TITLE
Fix grammar error in chapter 5. 

### ISSUE THREAD

**Issue by Ochirsaikhan** [amyjko/cooperative-software-development#152]
In the second sentence of the first paragraph of chapter 5, there is a grammatical error that needs to be fixed. 

The sentence is as follows: 

> "Evidence clearly shows that success is highly contextual and stakeholder-dependent: success might be financial, social, physical and even emotional, suggesting that software engineering success is a multifaceted variable that cannot explained simply by user satisfaction, profitability or meeting requirements, budgets and schedules."

The verb "explained" after the modal verb "can" does not appear to be in the correct form. Consider changing the verb form to "be explained." After fixing the grammatical error, the sentence should read:

> "Evidence clearly shows that success is highly contextual and stakeholder-dependent: success might be financial, social, physical and even emotional, suggesting that software engineering success is a multifaceted variable that cannot be explained simply by user satisfaction, profitability or meeting requirements, budgets and schedules."

**Comment by amyjko** [comment]
Thanks! Fixed.
