### ISSUE TITLE
requirements: alter phrasing

### ISSUE THREAD

**Issue by johnmaccormick** [amyjko/cooperative-software-development#159]
In the Requirements chapter, the penultimate sentence includes the words "requirements...is free from racist ideas". I can't be sure exactly what the intended meaning was, but perhaps something like "requirements...must be free from racist ideas" was intended?

PS. My Dickinson College senior seminar compsci class is enjoying great discussions based on each chapter of this book. Thanks again for the excellent text!

**Comment by amyjko** [comment]
Good catch, thanks for reporting!
