### ISSUE TITLE
Phrasing of Chapter 7: Architecture; Event-driven

### ISSUE THREAD

**Issue by Mikek16** [amyjko/cooperative-software-development#162]
In the description of the event-driven architectural style in chapter 7, this sentence is used: "Examples include most model-view-controller-based user interface frameworks, which have models broadest change events to views, so they may update themselves to render new model state." Should "broadest" be broadcast here and is "views" meant to be "viewers", as in the subscribers mentioned earlier? If so, maybe this should be changed back to subscribers for clarity.

**Comment by amyjko** [comment]
Good catch! I've clarified the terminology.
